/*
  This model will combine all of the blockgroup data for Philadelphia into a
  single table (Philadelphia has a `county_fips_code` of 101). The table should
  have the following fields:

  - geo_id
  - year
  - total_pop
  - pop_density
  - male_pop
  - female_pop
  - white_pop
  - black_pop
  - asian_pop
  - hispanic_pop
  - amerindian_pop
  - other_race_pop
  - two_or_more_races_pop
  - blockgroup_geom
  - blockgroup_key

  The model generated by this query should contain all the fields that pertain
  to blockgroups that we actually use downstream of the model. Additionally, a
  should always have some unique identifier for each record. In this case that
  will be the `blockgroup_key`, and can be made up of the `geo_id` and the
  `year`.

  The table should include data from 2010 until 2018.

  HINT: Construct a query for one year's data appropriately, and then copy/paste
  that for other years, and UNION ALL them together.
*/

SELECT 1
