/*
  This model will combine all of the blockgroup data for Philadelphia into a
  single table (Philadelphia has a `county_fips_code` of 101). The table should
  have the following fields:

  - geo_id
  - year
  - total_pop
  - pop_density
  - male_pop
  - female_pop
  - white_pop
  - black_pop
  - asian_pop
  - hispanic_pop
  - amerindian_pop
  - other_race_pop
  - two_or_more_races_pop
  - blockgroup_geom
  - blockgroup_key

  The model generated by this query should contain all the fields that pertain
  to blockgroups that we actually use downstream of the model. Additionally, a
  should always have some unique identifier for each record. In this case that
  will be the `blockgroup_key`, and can be made up of the `geo_id` and the
  `year`.
*/

SELECT
    2010 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2010' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2010_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2011 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2011' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2011_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2012 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2012' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2012_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2013 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2013' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2013_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2014 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2014' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2014_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2015 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2015' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2015_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2016 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2016' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2016_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2017 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2017' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2017_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'

UNION ALL

SELECT
    2018 AS year,
    geo_id,
    total_pop,
    total_pop / ST_AREA(blockgroup_geom) AS pop_density,
    male_pop,
    female_pop,
    white_pop,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    blockgroup_geom,
    geo_id || '_2018' AS blockgroup_key
FROM `bigquery-public-data.census_bureau_acs.blockgroup_2018_5yr`
JOIN `bigquery-public-data.geo_census_blockgroups.blockgroups_42` USING (geo_id)
WHERE county_fips_code = '101'
